version: '3.7'

services:

  geofarmtz:
    container_name: geofarmtz
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/gerofarmtz'
      - '/gerofarmtz/node_modules'
    ports:
      - 3001:3000
    stdin_open: true